version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" #location of go.mod
    schedule:
      interval: "daily" #"weekly"
      #day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      #- "automerge"
    
  #also keep github actions updated
  - package-system: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

    